### PR TITLE
Trigger a job

### PR DESCRIPTION
**Pull request by alexwelch**

### CODE REVIEW

**Comment by alexwelch** [comment]
need to make sure the image names match up with our templates before merging

**Comment by dharmamike** [comment]
The PR in its current state is only to create the new deployment target (with overriding of environment variables), right?  It doesn't yet display the status or the job or its steps as per https://www.pivotaltracker.com/story/show/86160454.

**Comment by alexwelch** [comment]
@dharmamike - you are correct, it only creates a job with overrides

**Comment by bdehamer** [comment]
:+1:

**Comment by dharmamike** [comment]
:+1:

**Pull request merged**
