### PR TITLE
Feature/straight up image

### PR DESCRIPTION
**Pull request by alexwelch**

### CODE REVIEW

**Comment by alexwelch** [comment]
screen shot 2015-03-12 at 10 25 54 am

@patocox, @ParkerFleming, @grindpattern, @rossjimenez Are we happy with this? I was thinking we may want to change the description on the result a bit. Also, the example search links to: https://github.com/CenturyLinkLabs/panamax-ui/wiki/How-to:-Add-Registries#running-an-image-from-a-private-repository and has title text: "Learn about search filters."

**Comment by rossjimenez** [comment]
LGTM ,,, why did we end up with != as the prefix ?

**Comment by alexwelch** [comment]
Good question. @ParkerFleming and I looked at google and github search characters, we also subtracted any characters that could exist in the docker image URI (i.e. valid docker image name chars + valid URI chars). We were gonna do just "!", but then Parker brought up it being hard to notice, so we added the "=". I also like the "=" because it kinda sets up the format for commands/filters going forward.

**Comment by argvader** [comment]
:+1:

**Pull request merged**
